muggle:
    resource: "@GoIntegroHateoasBundle/Controller"
    type: annotation

# Tiene que ir abajo de todo - tiene un action catch-all
magic_fetch:
    resource: '@GoIntegroHateoasBundle/Controller/MagicFetchController.php'
    type: annotation
magic_alter:
    resource: '@GoIntegroHateoasBundle/Controller/MagicAlterController.php'
    type: annotation

